
services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_DB=pharmacyhub
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7.2-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --requirepass myredispassword
    healthcheck:
      test: [ "PharmacyHub", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.2
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: pharmacyhub
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - "8080:8080"
    volumes:
      - ./pharmacyhub-realm/pharmacyhub_realm_local.json:/opt/keycloak/data/import/realm.json
      - keycloak-data:/opt/keycloak/data
    command:
      - "start-dev"
      - "--import-realm"
      - "--spi-theme-static-max-age=-1"
      - "--spi-theme-cache-themes=false"
      - "--spi-theme-cache-templates=false"
    depends_on:
      - postgres
      - redis

volumes:
  postgres-data:
  redis-data:
  keycloak-data: