services:
  postgres-prod:
    image: postgres:12.20-alpine3.20
    container_name: pharmacyhub-postgres-prod
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=pharmacyhub_prod
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${PROD_DB_PASSWORD}
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
      - ${CRM_BASE_PATH}/prod/data/backups/postgres:/backups
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - prod-network
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  redis-prod:
    image: redis:7.2-alpine
    container_name: pharmacyhub-redis-prod
    ports:
      - "6381:6379"
    volumes:
      - redis_data_prod:/data
    command: redis-server --appendonly yes --requirepass ${PROD_REDIS_PASSWORD}
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${PROD_REDIS_PASSWORD}", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - prod-network
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  # Keycloak service removed as it's not needed for PharmacyHub

  pgadmin-prod:
    image: dpage/pgadmin4:latest
    container_name: pharmacyhub-pgadmin-prod
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PROD_PGADMIN_EMAIL:-admin@pharmacyhub.com}
      - PGADMIN_DEFAULT_PASSWORD=${PROD_PGADMIN_PASSWORD:-admin}
      - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=True
      - PGADMIN_CONFIG_LOGIN_BANNER="Authorized users only. All activity may be monitored and reported."
      - PGADMIN_SERVER_JSON=[{"name":"PharmacyHub Production DB","host":"postgres-prod","port":5432,"db":"pharmacyhub_prod","username":"postgres","password":"${PROD_DB_PASSWORD}","maintenance_db":"postgres","group":"Servers"}]
    volumes:
      - pgadmin_data_prod:/var/lib/pgadmin
    ports:
      - "5052:80"
    networks:
      - prod-network
      - proxy-network
    depends_on:
      postgres-prod:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-O", "-", "http://localhost:80/misc/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  pharmacyhub-backend-prod:
    image: ${PROD_BACKEND_DOCKER_IMAGE}
    container_name: pharmacyhub-backend-prod
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=${PROD_SERVER_PORT}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-prod:5432/pharmacyhub_prod
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=${PROD_DB_PASSWORD}
      # Keycloak environment variables removed as they're not needed for PharmacyHub
      - REDIS_HOST=redis-prod
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${PROD_REDIS_PASSWORD}
      - JAVA_OPTS=-Xms512m -Xmx1024m
    volumes:
      - ${CRM_BASE_PATH}/prod/backend/logs:/app/logs
    networks:
      - prod-network
      - proxy-network
    depends_on:
      postgres-prod:
        condition: service_healthy
      redis-prod:
        condition: service_healthy
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
      resources:
        limits:
          cpus: '2'
          memory: 2G
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

networks:
  prod-network:
    name: pharmacyhub-prod-network
    external: true
  proxy-network:
    name: proxy-network
    external: true

volumes:
  postgres_data_prod:
    name: pharmacyhub_postgres_data_prod
    driver: local
    driver_opts:
      type: none
      device: ${CRM_BASE_PATH}/prod/data/postgres
      o: bind
  redis_data_prod:
    name: pharmacyhub-redis-data-prod
    driver: local
    driver_opts:
      type: none
      device: ${CRM_BASE_PATH}/prod/data/redis
      o: bind
  pgadmin_data_prod:
    name: pharmacyhub-pgadmin-data-prod
    driver: local
    driver_opts:
      type: none
      device: ${CRM_BASE_PATH}/prod/data/pgadmin
      o: bind
