version: '3.8'

services:
  postgres-prod:
    image: postgres:12.20-alpine3.20
    container_name: crm-postgres-prod
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=crm_prod
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${PROD_DB_PASSWORD}
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
      - ${CRM_BASE_PATH}/prod/data/backups/postgres:/backups
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - prod-network
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  redis-prod:
    image: redis:7.2-alpine
    container_name: crm-redis-prod
    ports:
      - "6381:6379"
    volumes:
      - redis_data_prod:/data
    command: redis-server --appendonly yes --requirepass ${PROD_REDIS_PASSWORD}
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${PROD_REDIS_PASSWORD}", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - prod-network
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  keycloak-prod:
    image: quay.io/keycloak/keycloak:25.0.2
    container_name: crm-keycloak-prod
    environment:
      - KEYCLOAK_ADMIN=${PROD_KEYCLOAK_ADMIN_USER}
      - KEYCLOAK_ADMIN_PASSWORD=${PROD_KEYCLOAK_ADMIN_PASSWORD}
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres-prod:5432/crm_prod
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=${PROD_DB_PASSWORD}
      - KC_HOSTNAME=${PROD_KEYCLOAK_HOST}
      - KC_PROXY=edge
      - KC_PROXY_ADDRESS_FORWARDING=true
    volumes:
      - ../../../themes:/opt/keycloak/providers
      - keycloak_data_prod:/opt/keycloak/data
    command:
      - "start"
      - "--optimized"
    networks:
      - prod-network
      - proxy-network
    depends_on:
      postgres-prod:
        condition: service_healthy
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  crm-backend-prod:
    image: ${PROD_BACKEND_DOCKER_IMAGE}
    container_name: crm-backend-prod
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=${PROD_SERVER_PORT}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-prod:5432/crm_prod
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=${PROD_DB_PASSWORD}
      - KEYCLOAK_AUTH_SERVER_URL=http://keycloak-prod:8080
      - KEYCLOAK_REALM=${PROD_KEYCLOAK_REALM}
      - KEYCLOAK_RESOURCE=${PROD_KEYCLOAK_CLIENT_ID}
      - KEYCLOAK_CREDENTIALS_SECRET=${PROD_KEYCLOAK_CLIENT_SECRET}
      - REDIS_HOST=redis-prod
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${PROD_REDIS_PASSWORD}
      - JAVA_OPTS=-Xms512m -Xmx1024m
    volumes:
      - ${CRM_BASE_PATH}/prod/backend/logs:/app/logs
    networks:
      - prod-network
      - proxy-network
    depends_on:
      postgres-prod:
        condition: service_healthy
      keycloak-prod:
        condition: service_started
      redis-prod:
        condition: service_healthy
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
      resources:
        limits:
          cpus: '2'
          memory: 2G
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

networks:
  prod-network:
    name: crm-prod-network
    driver: bridge
  proxy-network:
    name: proxy-network
    external: true

volumes:
  postgres_data_prod:
    name: crm_postgres_data_prod
    driver: local
    driver_opts:
      type: none
      device: ${CRM_BASE_PATH}/prod/data/postgres
      o: bind
  keycloak_data_prod:
    name: crm-keycloak-data-prod
    driver: local
    driver_opts:
      type: none
      device: ${CRM_BASE_PATH}/prod/data/keycloak
      o: bind
  redis_data_prod:
    name: crm-redis-data-prod
    driver: local
    driver_opts:
      type: none
      device: ${CRM_BASE_PATH}/prod/data/redis
      o: bind
