spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pharmacyhub
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000

  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          batch_size: 50
          batch_versioned_data: true
          order_inserts: true
          order_updates: true
        fetch_size: 100
    open-in-view: false

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: pharmacyhub-client
            client-secret: gH5vlF79Wm5jOaKawkPzjB4tA0jfaLAJ
            authorization-grant-type: authorization_code
            scope:
              - openid
              - profile
              - email
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/pharmacyhub-realm
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/pharmacyhub-realm
  #Configurations to send email
  mail:
    username: syedus06@gmail.com
    password: lyce duoh tkeh uqtr
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true


server:
  port: 8081

executor:
  core-pool-size: 50
  max-pool-size: 100
  queue-capacity: 1000

app:
  frontend:
    url: http://localhost:3000
keycloak:
  admin:
    username: admin
    password: admin
  realm: pharmacyhub-realm

data:
  load:
    enabled: true

calcom:
  url: http://localhost:3001

pharmacyhub:
  seeder:
    engine: true
  test:
    data:
      pharmacist: 1-10
      proprietor: 21-30
      salesman: 31-40
      pharmacy:
           manager: 11-20


clientApp:
  name: PharmacyHub

