spring:
  profiles:
    active: local
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:myredispassword}
      timeout: 10000ms
      connect-timeout: 10000ms
      client-type: lettuce
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
      database: 0

server:
  port: 8081

logging:
  level:
    org.springframework.security: ERROR
    org.springframework.security.oauth2: ERROR
    org.springframework.web: DEBUG
    org.keycloak: ERROR

app:
  cache:
    configurations:
      calls:
        type: REDIS
        ttlSeconds: 3600
        maxSize: 1000
        enableStatistics: true
      call-categories:
        type: REDIS
        ttlSeconds: 3600
        maxSize: 1000
      call-statuses:
        type: REDIS
        ttlSeconds: 3600
        maxSize: 500
      call-types:
        type: REDIS
        ttlSeconds: 3600
        maxSize: 500
      channel-types:
        type: REDIS
        ttlSeconds: 3600
        maxSize: 500
      cities:
        type: REDIS
        ttlSeconds: 3600
        maxSize: 1000
      inquiries:
        type: REDIS
        ttlSeconds: 3600
        maxSize: 1000
      parties:
        type: REDIS
        ttlSeconds: 3600
        maxSize: 2000
      priorities:
        type: REDIS
        ttlSeconds: 3600
        maxSize: 500
      products:
        type: REDIS
        ttlSeconds: 3600
        maxSize: 2000
      sources:
        type: REDIS
        ttlSeconds: 3600
        maxSize: 500
      sub-call-types:
        type: REDIS
        ttlSeconds: 3600
        maxSize: 1000
      user-profiles:
        type: REDIS
        ttlSeconds: 1800
        maxSize: 5000
      keycloak-users:
        type: REDIS
        ttlSeconds: 1800
        maxSize: 10000
        enableStatistics: true
      keycloak-groups:
        type: REDIS
        ttlSeconds: 900
        maxSize: 5000
        enableStatistics: true
      keycloak-roles:
        type: CAFFEINE
        ttlSeconds: 300
        maxSize: 1000
        enableStatistics: true

keycloak:
  realm: ${KEYCLOAK_REALM}
  auth-server-url: ${KEYCLOAK_URL}
  ssl-required: external
  resource: ${KEYCLOAK_CLIENT_ID}
  credentials:
    secret: ${KEYCLOAK_CLIENT_SECRET}
  use-resource-role-mappings: true
  bearer-only: true
  admin:
    username: ${KEYCLOAK_ADMIN_USERNAME}
    password: ${KEYCLOAK_ADMIN_PASSWORD}