spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pharmacyhub
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: pharmacyhub-client
            client-secret: oe96iYNG9C7BPAfaToyFxv02FylVzxTX
            authorization-grant-type: authorization_code
            scope:
              - openid
              - profile
              - email
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/pharmacyhub
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/pharmacyhub

  mail:
    username: syedus06@gmail.com
    password: lyce duoh tkeh uqtr
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

server:
  port: 8081
  forward-headers-strategy: native

app:
  frontend:
    url: "https://prod.pharmacyhub.com/"  # Replace with your actual frontend URL

keycloak:
  admin:
    username: admin
    password: admin
  realm: pharmacyhub

data:
  load:
    enabled: true

pharmacyhub:
  seeder:
    engine: true
  test:
    data:
      pharmacist: 1-10
    pharmacy:
      manager: 11-20
      proprietor: 21-30
      salesman: 31-40

clientApp:
  name: PharmacyHub