spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pharmacyhub
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  mail:
    username: syedus06@gmail.com
    password: lyce duoh tkeh uqtr
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8081

clientApp:
  name: PharmacyHub

pharmacyhub:
  seeder:
    engine: false
  test:
    data:
      pharmacist: 1-10
      pharmacy-manager: 11-20
      proprietor: 21-30
      salesman: 31-40