spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pharmacyhub
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  mail:
    username: syedus06@gmail.com
    password: lyce duoh tkeh uqtr
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  # Auto-create log directory
  application:
    name: pharmacyhub
  mvc:
    throw-exception-if-no-handler-found: true
  web.resources.add-mappings: false

server:
  port: 8080
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
  error:
    include-stacktrace: never
    include-message: always
    include-binding-errors: always
    whitelabel.enabled: false

# Logging configuration
logging:
  file:
    name: logs/pharmacyhub.log
    max-size: 10MB
    max-history: 30
  level:
    root: INFO
    com.pharmacyhub: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.hibernate: INFO
    # Enable Spring Security debug logging temporarily for troubleshooting
    org.springframework.security.access: DEBUG
    org.springframework.security.authentication: DEBUG
    org.springframework.security.authorization: DEBUG

clientApp:
  name: PharmacyHub

pharmacyhub:
  seeder:
    engine: true
  test:
    data:
      pharmacist: 1-10
      pharmacy-manager: 11-20
      proprietor: 21-30
      salesman: 31-40
  security:
    jwt:
      secret: pharmacyhub_jwt_secret_key_for_token_generation_and_validation_2025
      token-validity-in-seconds: 18000  # 5 hours
  error-handling:
    include-debug-info: false  # Set to true in development environment
    log-request-details: true
    generic-error-message: "An unexpected error occurred. Please try again later or contact support."
