# Removed version attribute to avoid warnings

services:
  # Nginx Proxy Manager - Reverse Proxy with SSL Support
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - '80:80'   # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81'   # Admin Web Port (Default credentials: admin@example.com / changeme)
    environment:
      # Database connection settings
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
    volumes:
      - ./data:/data
      - ./data/nginx:/etc/nginx/conf.d
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      db:
        condition: service_healthy
    networks:
      - proxy-network
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:81"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # MariaDB database for Nginx Proxy Manager
  db:
    image: 'mariadb:10.6.13'
    container_name: npm-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "npm"
      MYSQL_DATABASE: "npm"
      MYSQL_USER: "npm"
      MYSQL_PASSWORD: "npm"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - proxy-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent", "-h", "localhost", "-u", "root", "-pnpm"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  # Portainer - Docker Container Management
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer_data:/data
    ports:
      - "9000:9000"
    networks:
      - proxy-network
    command: -H unix:///var/run/docker.sock  # Ensure Docker mode
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:9000"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

networks:
  proxy-network:
    name: proxy-network
    external: true

volumes:
  portainer_data:
    name: portainer_data
