version: '3.8'

services:
  # Nginx Proxy Manager - Reverse Proxy with SSL Support
  npm:
    image: 'jc21/nginx-proxy-manager:2.12.3'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - '80:80'   # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81'   # Admin Web Port (Default credentials: admin@example.com / changeme)
    environment:
      # Database connection settings
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
    volumes:
      - ./data:/data
      # Create volume binding for configuration to ensure persistence
      - ./data/config.json:/app/config/production.json
      - ./data/nginx:/etc/nginx/conf.d
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      db:
        condition: service_healthy
    networks:
      - proxy-network
    healthcheck:
      # Use wget instead of curl for Alpine-based images
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:81"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # MariaDB database for Nginx Proxy Manager
  db:
    # Use the official MariaDB image for better compatibility
    image: 'mariadb:10.6.13'
    container_name: npm-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "npm"
      MYSQL_DATABASE: "npm"
      MYSQL_USER: "npm"
      MYSQL_PASSWORD: "npm"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - proxy-network
    healthcheck:
      # Use a more reliable healthcheck command
      test: ["CMD", "mysqladmin", "ping", "--silent", "-h", "localhost", "-u", "root", "-pnpm"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    # Ensure proper character encoding
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  # Portainer - Docker Container Management
  portainer:
    # Use an updated Portainer version
    image: portainer/portainer-ce:2.18.4
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer_data:/data
    ports:
      - "9000:9000"
    networks:
      - proxy-network
    healthcheck:
      # Use wget instead of curl
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:9000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  proxy-network:
    name: proxy-network
    # Leave as external: true as this is used by the GitHub Actions workflow
    external: true

volumes:
  portainer_data:
    name: portainer_data
